include: package:lints/recommended.yaml

linter:
  rules:
    avoid_function_literals_in_foreach_calls: false

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  errors:
    todo: false
