include: package:lints/recommended.yaml

linter:
  rules:
    avoid_function_literals_in_foreach_calls: false

analyzer:
  errors:
    todo: false
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
